services:
  - type: web
    name: onetimelink-demo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn onetimelink_demo.wsgi:application
