services:
  - type: web
    name: onetimelink-demo
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate && gunicorn onetimelink_demo.wsgi:application
    plan: free
